### ISSUE TITLE
Question about ElementwiseKernel speed performance

### ISSUE THREAD

**Issue by doyaklee** [PacktPublishing/Hands-On-GPU-Programming-with-Python-and-CUDA#1]
I have a question about `ElementwiseKernel` speed performance, specifically in the example code of `simple_element_kernel_example0.py`.

I twisted this sample code to fit into Python3 environment just by changing `print` function parts as follows:
```python
import numpy as np
import pycuda.autoinit    # initialize pycuda
from pycuda import gpuarray
from time import time
from pycuda.elementwise import ElementwiseKernel

host_data = np.float32( np.random.random(50000000) )

gpu_2x_ker = ElementwiseKernel(
"float *in, float *out",
"out[i] = 2*in[i];",
"gpu_2x_ker")

def speedcomparison():
    t1 = time()
    host_data_2x =  host_data * np.float32(2)
    t2 = time()
    print('total time to compute on CPU: %f' % (t2 - t1))
    device_data = gpuarray.to_gpu(host_data)
    # allocate memory for output
    device_data_2x = gpuarray.empty_like(device_data)
    t1 = time()
    gpu_2x_ker(device_data, device_data_2x)
    t2 = time()
    from_device = device_data_2x.get()
    print('total time to compute on GPU: %f' % (t2 - t1))
    print('Is the host computation the same as the GPU computation? : {}'.format(np.allclose(from_device, host_data_2x) ))
    

if __name__ == '__main__':
    speedcomparison()
```

By reading this book, I know there is a compilation issue so that it takes way more time for the first run. So I ran this code several times, but even after 10 times run, my result doesn't look good.
```
total time to compute on CPU: 0.076065
total time to compute on GPU: 1.330138
Is the host computation the same as the GPU computation? : True
```

In `time_calc0.py` example, I got the result I expected with the code and the result as follows:
```python
import numpy as np
import pycuda.autoinit
from pycuda import gpuarray
from time import time

host_data = np.float32( np.random.random(50000000) )

t1 = time()
host_data_2x =  host_data * np.float32(2)
t2 = time()

print('total time to compute on CPU: %f' % (t2 - t1))


device_data = gpuarray.to_gpu(host_data)

t3 = time()
device_data_2x =  device_data * np.float32(2)
t4 = time()

from_device = device_data_2x.get()


print('total time to compute on GPU: %f' % (t4 - t3))
print('GPU is %f times faster than CPU'  % ((t2-t1)/(t4 - t3)))
print('Is the host computation the same as the GPU computation? : {}'.format(np.allclose(from_device, host_data_2x) ))
```
```
total time to compute on CPU: 0.097082
total time to compute on GPU: 0.010009
GPU is 9.699898 times faster than CPU
Is the host computation the same as the GPU computation? : True
```

Could you point out what I missed or did wrong? Thanks.

For your information, my environment is as follows:
* O/S : Windows10
* CPU : AMD 3950x
* GPU : 1080ti
* Python : Anaconda 3.7 64bit
* pycuda : 2019.1.2
* Visual C++ Compiler : 19.12.25835
* CUDA : 10.2

**Comment by btuomanen** [comment]
There's probably an internal issue with how PyCUDA handles cacheing compiled code; it's kind of arbitrary, really, I've found.

I'd try running it from ipython within the same session. (Load up ipython on the command line, then type "run whatever.py", and then run again.)

Thanks for your interest. Btw I'm writing the second edition which is switching to python 3 if you want to be a reviewer. Packt are a bunch of cheapskates and they won't pay you, but you'll get acknowledged at the beginning of the book which can help for finding a job and I'll write a ref on LinkedIn at the end. I'll also send you a hard copy in the mail when it's done. (I'll have to warn you, the Packt people are absolutely annoying to deal with.)

It's been delayed and we're rebooting it due to a lackadaisical editor who was just fired finally.
________________________________

**Comment by doyaklee** [comment]
Thanks for your quick reply. 

Originally, I ran it within the same session of Jupyter notebook. Based on your comment, I ran it on Windows cmd and IPython shell, but results were about the same.

If this is due to the way how PyCUDA handles caching compiled code as you mentioned, I would just move on to the next parts of the book.

About your suggestion, I'm happy to be a reviewer for the new edition since I strongly prefer to use Python 3. But I'm not sure whether I'm suited to be a reviewer since I'm not in the programming industry(I'm working for the accounting/finance department) and I live in Korea. Even in this situation if you want me to be a reviewer, please let me know.

Also, please feel free to close this issue if you want!

> There's probably an internal issue with how PyCUDA handles cacheing compiled code; it's kind of arbitrary, really, I've found. I'd try running it from ipython within the same session. (Load up ipython on the command line, then type "run whatever.py", and then run again.) Thanks for your interest. Btw I'm writing the second edition which is switching to python 3 if you want to be a reviewer. Packt are a bunch of cheapskates and they won't pay you, but you'll get acknowledged at the beginning of the book which can help for finding a job and I'll write a ref on LinkedIn at the end. I'll also send you a hard copy in the mail when it's done. (I'll have to warn you, the Packt people are absolutely annoying to deal with.) It's been delayed and we're rebooting it due to a lackadaisical editor who was just fired finally.

**Comment by gaurav-packt** [comment]
Closing the issue as suggested
